### ISSUE TITLE
Use Polkadot instead of Connect

### ISSUE THREAD

**Issue by v1rtl** [vixalien/explosiv#1]
[Polkadot](https://github.com/lukeed/polkadot) is even more minimal than Connect so it might be worth looking at.

**Comment by vixalien** [comment]
Hey 👋 polkadot is great but I think it will break Explosiv (leading to large code rewrite). For example:

- The `connect` and `morgan` will probably not work anymore (Polkadot does not use `next`)
- It will add features not necessary to Explosiv (like async/await)
- Polkadot has removed all Express compatible code. I believe `sirv` (a static file server like`express.static`) only works in Express & compatible libraries (hence connect)

**Comment by v1rtl** [comment]
Thanks for the detailed response!

I was just thinking of something newer than Connect that would be even more compact

but when Polkadot doesn't fit then it's ok to keep using Connect

**Comment by vixalien** [comment]
Yes I know ya'll hate connect and Express but the thing that most other libraries don't understand is their nature: Do one thing, Do it well!

I like how connect allow me to use middleware without other bloated functions. Like who need promises anyways? NodeJS have been built on callbacks and doesn't look like it's moving to Promises soon. I don't need a library, how lightweight should it be, that provides me with an unnecessarily complex router just to use middleware!
